# Generated by Django 3.0.6 on 2020-05-31 05:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_post_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='post',
            name='customer',
        ),
        migrations.AddField(
            model_name='post',
            name='customer',
            field=models.ManyToManyField(to='accounts.Customer'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(),
        ),
    ]
