# Generated by Django 3.0.6 on 2020-06-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='post_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
